# Generated by Django 4.1.4 on 2022-12-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0002_capitulo_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mr_app.page'),
        ),
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.CreateModel(
            name='ForumPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('fk_forumpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_app.forumpost')),
            ],
        ),
    ]
