# Generated by Django 4.1.4 on 2022-12-20 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0003_forumpost_comment_fk_page_manga_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 17, 47, 31, 963718)),
        ),
        migrations.AddField(
            model_name='forumpostcomment',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 17, 47, 31, 964230)),
        ),
    ]
