# Generated by Django 4.1.4 on 2022-12-20 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0004_forumpost_publish_date_forumpostcomment_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 17, 48, 32, 318758, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forumpostcomment',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 17, 48, 32, 319280, tzinfo=datetime.timezone.utc)),
        ),
    ]
