# Generated by Django 4.1.4 on 2022-12-20 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0005_alter_forumpost_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 17, 50, 50, 986906, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forumpostcomment',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 17, 50, 50, 987414, tzinfo=datetime.timezone.utc)),
        ),
    ]
