# Generated by Django 4.1.4 on 2022-12-20 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0009_alter_forumpost_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='forumpostcomment',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
