# Generated by Django 4.1.4 on 2022-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0010_alter_forumpost_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
