# Generated by Django 4.1.4 on 2022-12-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0012_alter_manga_author_alter_manga_image_alter_page_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(default=None, upload_to='media/manga/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.ImageField(upload_to='media/page/'),
        ),
    ]
