# Generated by Django 4.1.4 on 2022-12-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0015_rename_fk_manga_capitulo_manga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_nascimento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tipo',
            new_name='type',
        ),
    ]
