# Generated by Django 4.1.4 on 2022-12-26 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0017_forumpostcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpostcomment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
