# Generated by Django 4.1.4 on 2022-12-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0018_alter_forumpostcomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='page',
        ),
        migrations.AddField(
            model_name='comment',
            name='Capitulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mr_app.capitulo'),
        ),
    ]
