# Generated by Django 4.1.4 on 2022-12-26 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0020_remove_comment_title_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
