# Generated by Django 4.1.4 on 2023-01-20 12:06

from datetime import datetime
from django.db import migrations

def seed_the_bd(apps, schema_editor):
    Manga = apps.get_model('mr_app', 'Manga')
    
    Manga.objects.create(title="Boku No Hero",
    release_date=datetime(year=2014, month=7, day=7),
    author="Kōhei Horikoshi",
    description = "Boku no Hero Academia, também conhecido como My Hero Academia no ocidente, é uma série de mangá escrita e ilustrada por Kōhei Horikoshi. Os capítulos do mangá são publicados na revista Weekly Shōnen Jump desde julho de 2014, sendo compilados em volumes formato tankōbon pela editora Shueisha."[0:45],
    tags = " Ficção de aventura, Fantasia científica, História de super-herói, Comédia, Ficção científica",
    image = "seed/bokunohero.jpg")

    Manga.objects.create(title="Berserk",
    release_date=datetime(year=1989, month=8, day=1),
    author="Kentaro Miura",
    description = 'Berserk é uma série de mangá escrita e ilustrada por Kentaro Miura. Situado em um mundo de fantasia sombria inspirado na Europa medieval, a história gira em torno de Guts, um solitário mercenário, e Griffith, o líder de um bando de mercenários chamado de "Bando do Falcão"'[0:45],
    tags = "Fantasia sombria, Alta fantasia, Espada e feitiçaria",
    image = "seed/berserk.jpg")

    Manga.objects.create(title="One Punch-Man", 
    release_date=datetime(year=2009, month=7, day=3),
    author="Yusuke Murata",
    description = "One Punch-Man é uma série de webcomic criada pelo autor com o pseudónimo One, e é publicada desde 2009. A série rapidamente tornou-se um fenómeno viral, alcançando mais de 7,9 milhões de acessos, em junho de 2012."[0:45],
    tags = "Ação, Comédia, Superhero comics",
    image = "seed/one.jpg")
    

class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0021_comment_publish_date'),
    ]

    operations = [
        migrations.RunPython(seed_the_bd)
    ]
